import { GeistSans } from 'geist/font/sans'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { ApolloClientProvider } from "@/providers/ApolloClientProvider";
import { ThemeProvider } from '@/providers/ThemeProvider';
import { ToastProvider } from '@/providers/ToastProvider';

const inter = Inter({ subsets: ["latin"] });

import '@/styles/globals.css'
import '@/styles/themes.css'
import { ColorSwitcher } from '@/components/ui/elements/ColorSwitcher';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={GeistSans.variable}>
          <ColorSwitcher/>
          <ApolloClientProvider>
            <NextIntlClientProvider messages={messages}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                disableTransitionOnChange
              >
                <ToastProvider/>
                {children}
              </ThemeProvider>
            </NextIntlClientProvider>
          </ApolloClientProvider>
      </body>
    </html>
  );
}
